language: node_js

node_js:
  - "5"
  - "4"
  - "0.12"

sudo: false
cache:
  directories:
    - node_modules

matrix:
  fast_finish: true

before_install:
  # For 0.12 without harmony
  - npm install gnode

script: "make test-travis"
after_script: "npm install coveralls@2.10.0 && cat ./coverage/lcov.info | coveralls"

notifications:
  email:
    on_success: change
    on_failure: always
